### ISSUE TITLE
Plugin detection not working

### ISSUE THREAD

**Issue by vikasprogrammer** [wpscanteam/wpscan-v3#25]
I tried the default options to scan using wpscan v2.x and the plugins are enumerated with version numbers 

`wpscan -u http://url.co.uk/ --random-agent`

However I tried all the various combinations in v3, but plugin enumeration does not identify the version in passive mode and active mode take a lot of time. Commands i tried:

Not able to identify the versions - `wpscan -u http://url.co.uk/ --random-agent -e p,vt,tt,cb,u,m --detection-mode passive`

Takes a lot of time - `wpscan -u http://url.co.uk/ --random-agent -e vp`

Am I doing something wrong? How can I simulate default behaviour of v2 in v3?

**Comment by erwanlr** [comment]
The default behaviour in the v2 (w/o the -e option) is to passively scan for plugins and check their versions aggressively. Which is not really suitable and users may thinks that all plugins were checked.

With the detection mode system in the v3, users have to explicitly supply what they want to check and how (otherwise, vulnerable plugins and their versions are checked passively and aggressively, called mixed mode).

```-e p``` to enumerate the most popular plugins, ```vp``` the vulnerable ones and ```ap``` for all plugins, then the --detection-mode or --plugins-detection mode can also be used. A custom list of plugins can also be provide with the ```plugins-list``` option.

So, in your case that would be ```-e ap --plugins-detection passive```.

And yes, the enumeration can take a long time with aggressive or mixed mode, especially against instances with preventive measures in place (such as security plugins and so on)

**Comment by vikasprogrammer** [comment]
I still get this - The version could not be determined.

**Comment by vikasprogrammer** [comment]
Except one - 

```
[+] wordpress-seo
 | Location: http://humourhub.co.uk/wp-content/plugins/wordpress-seo/
 | Last Updated: 2017-09-06T07:49:00.000Z
 | [!] The version is out of date, the latest version is 5.4
 |
 | Detected By: Comments (Passive Detection)
 |
 | Version: 5.2 (80% confidence)
 | Detected By: Comments (Passive Detection)
 |  - http://humourhub.co.uk/, Match: 'optimized with the Yoast SEO plugin v5.2 -'
```

**Comment by vikasprogrammer** [comment]
I get really inconsistent results from wpscan v2 and v3. How can I make sure the results are same? Most of the time v2 provides more accurate results.

**Comment by erwanlr** [comment]
Fixed, please use the --plugins-version-detection / --themes-version-detection options with the latest version of wpscan (v3.0.5)

Example:

```
wpscan --url http://wp.lab/wordpress-4.8.2/ -e ap --detection-mode passive --plugins-version-detection aggressive
```

Which will use passive methods to detect everything like the plugins, but aggressive methods for the plugin's versions

```
[+] Enumerating All Plugins

[i] Plugin(s) Identified:

[+] mailchimp-for-wp
 | Location: http://wp.lab/wordpress-4.8.2/wp-content/plugins/mailchimp-for-wp/
 | Latest Version: 4.1.9 (up to date)
 | Last Updated: 2017-09-19T12:09:00.000Z
 |
 | Detected By: Urls In Homepage (Passive Detection)
 |
 | Version: 4.1.9 (80% confidence)
 | Detected By: Readme - Stable Tag (Aggressive Detection)
 |  - http://wp.lab/wordpress-4.8.2/wp-content/plugins/mailchimp-for-wp/readme.txt
```

**Comment by vikasprogrammer** [comment]
I get this 

`Scan Aborted: type mismatch: String given`

**Comment by erwanlr** [comment]
Did you build with the GitHub repo ? (or are using the docker container ?). If so that's normal and will be fixed when the new version will be out. IN the menthe, the latest stable version (available via ```gem install wpscan``` should be used)

If not, then please use the --verbose option to see where the error occurs exactly

**Comment by vikasprogrammer** [comment]
I was using the build with github and did a git pull and bundle update. I
need hain output so can't go for v2 at the moment. I will try verbose and
let u know.

Sent from mobile

On 11-Oct-2017 7:08 PM, "Erwan" <notifications@github.com> wrote:

Did you build with the GitHub repo ? (or are using the docker container ?).
If so that's normal and will be fixed when the new version will be out. IN
the menthe, the latest stable version (available via gem install wpscan
should be used)

If not, then please use the --verbose option to see where the error occurs
exactly

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wpscanteam/wpscan-v3/issues/25#issuecomment-335812497>,
or mute the thread
